import { SoreWindowGlobal, NavigatorSideButton } from "WindowGlobal.slint";

component SoreButton inherits Rectangle {
    background: #1B3C53;
    width: SoreWindowGlobal.SideBarWidth;
    height: SoreWindowGlobal.Height / 3;

    @children
}

export component Navigator {
    x: 0;
    y: 0;

    VerticalLayout {
        alignment: start;
        for svg in [
            @image-url("assets/speedometer.svg"),
            @image-url("assets/stack.svg"),
            @image-url("assets/sun.svg"),
        ]: sideButton := SoreButton {
            Image {
                source: svg;
                colorize: white;
            }
        }
    }

    // HorizontalLayout {
    //     Text {
    //         text: "HorizontalLayout";
    //     }
    // }
}
