import { SoreWindowGlobal, NavigatorSideButton } from "WindowGlobal.slint";
import { Theme } from "GlobalStyles.slint";
import { SoreButton } from "SoreButtton.slint";
import { MainWindow } from "MainWindow.slint";
import { OverviewPage } from "Overview.slint";
import { About } from "About.slint";

export component Navigator {
    x: 0;
    y: 0;

    VerticalLayout {
        alignment: start;
        for svg in [
            @image-url("assets/speedometer.svg"),
            @image-url("assets/stack.svg"),
            @image-url("assets/sun.svg"),
        ]: sideButton := SoreButton {
            Image {
                source: svg;
                colorize: white;
            }
        }
    }

    MainWindow {
        About { }       
        // OverviewPage { }
    }
}
